### ISSUE TITLE
Breakpoint iPad e iPad pro

### ISSUE THREAD

**Issue by matteodesanti** [teamdigitale/italia-landing#16]
Su risoluzioni iPad e iPad pro (landscape) la visualizzazione non dovrebbe risultare linearizzata, come se fossimo in uno smartphone, ma simile a quello che si vede su desktop

**Comment by francescozaia** [comment]
@vito80ba chiedo giusto per scrupolo visto che mi avevi già scritto che avevi fatto questo controllo: si può chiudere questa issue?

**Comment by vito80ba** [comment]
Sì
