### ISSUE TITLE
pre-loader

### ISSUE THREAD

**Issue by matteodesanti** [teamdigitale/italia-landing#19]
Occorre aggiungere un pre-loader, almeno per la landing page (ora è troppo pesante ed alcuni asset si caricano in ritardo) ad esempio il mockup di sfondo.

**Comment by francescozaia** [comment]
Il setup del preloader è ora presente a sito, al momento è visibile per poco perché necessita di ottimizzazioni lato JS che saranno effettuate in #32. Anche sfondi e mockup hanno una gestione migliorata.
