### ISSUE TITLE
Thank you page newsletter

### ISSUE THREAD

**Issue by matteodesanti** [teamdigitale/italia-landing#25]
Modificare in mailup la thank you page dopo l'iscrizione alla newsletter. Se possibile evitare la thank you page e dare un messaggio di conferma appena sotto il campo di input, che in caso di successo viene disabilitato

**Comment by gunzip** [comment]
si, dovrebbe esserci scritto (sotto il campo) "ti è stata inviata un'email di conferma " perché comunque mailup deve verificare l'indirizzo

**Comment by francescozaia** [comment]
Per ora redirige a pagine create ad-hoc https://github.com/teamdigitale/italia-landing/commit/d83efb1e2aae26edb17a9f992cae21fa13448556
