### ISSUE TITLE
Tabella servizi

### ISSUE THREAD

**Issue by matteodesanti** [teamdigitale/italia-landing#27]
Nella tabella la didascalia e le etichette delle colonne dovrebbero trovarsi sopra e non sotto le altre righe.

**Comment by francescozaia** [comment]
@matteodesanti, @sbronzolo diceva esattamente l'opposto nella sua review 😄

**Comment by matteodesanti** [comment]
@francescozaia confermo la necessità di spostare didascalie e le testate in alto: su mobile altrimenti la tabella non risulta comprensibile.
