### ISSUE TITLE
Ottimizzazione peso asset e librerie esterne

### ISSUE THREAD

**Issue by matteodesanti** [teamdigitale/italia-landing#32]
Il sito è mediamente troppo pesante. Alcuni asset possono essere compressi maggiormente.
Va valutato il peso complessivo di alcune librerie esterne.

**Comment by francescozaia** [comment]
Una prima ottimizzazione, principalmente riguardante le immagini, è stata fatta portando così il sito da 1,7Mb a 1,0Mb.
Anche qualche script è ora caricato in modo asincrono, permettendo quindi al layout di iniziare a vedersi, anche se il peso dei file rimane ovviamente lo stesso.
