### ISSUE TITLE
Disattivare l'audio

### ISSUE THREAD

**Issue by Mte90** [teamdigitale/italia-landing#6]
Ho aperto il sito per curiosare e mi sono stupito di sentire dell'audio da una delle mie schede. 
Cioè bellissimo il sito con le animazioni ma l'audio no per favore almeno mettete un pulsante per disattivarlo. 
Io so come si silenziano le schede ma non è da tutti, mi fa ripensare ai siti fatti in flash.

**Comment by francescozaia** [comment]
Aggiunta icona mute #8
